name: busrt
description: A sample command-line application.
version: 0.1.0
repository: https://github.com/AndreiLosev/busrt/tree/impl-dart-client/bindings/dart/busrt

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  mutex: ^3.1.0
  typed_data: ^1.3.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
